# Config file for the test bench PWM hat


CHANNEL_CONFIGS:

  ExampleServo1:
    input_channel: 0              # The index of the input data array. In Python, indexing is zero-based, meaning the first value is at index 0.
    output_channel: 0             # The PWM hat output channel, same as printed on the PCB. Also Zero-based!
    type: angle                   # type of the controlled thing. this is very WIP, just use "angle" for now
    affects_pump: false           # Set to True if you want this channel to increase pump speed when the servo is moved.
    offset: 0                     # Servo start point offset. 0 is the middle of the servo range (90).
    direction: 1                  # Set to -1 to change operation direction.
    multiplier_positive: 40       # Servo movement scaling factors. About the same as degrees. pos+neg is the full range of the servo.
    multiplier_negative: 40
    gamma_positive: 0.2           # Gamma correction factors for input values.
    gamma_negative: 0.2           # = 1.0: Linear response (no correction).
                                  # < 1.0: Makes the servo more responsive at the beginning of joystick movement
                                  # > 1.0: Makes the servo more responsive at the end of joystick movement.
